
http://www.jessicayung.com/using-generators-in-python-to-train-machine-learning-models/

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os
os.getcwd()

'/content'

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

In [ ]:
classifier = Sequential()

In [ ]:
# Step 1 - Convolution
classifier.add(Conv2D(32,(3,3), input_shape=(64,64,3), activation='relu'))

# Step 2 - Pooling
classifier.add(MaxPooling2D(pool_size=(2,2)))


# Adding a second convolutional layer
classifier.add(Conv2D(32, (3,3), activation='relu'))
classifier.add(MaxPooling2D(pool_size=(2,2)))

# Step 3 - Flattening
classifier.add(Flatten())

# Step 4 - Full connection
classifier.add(Dense(units=128, activation='relu'))
classifier.add(Dense(units= 3, activation='softmax')) # 3 units because we have 3 classes of pokemon


# Compiling the CNN
classifier.compile(optimizer='adam', loss ='categorical_crossentropy', metrics=['accuracy'])



In [ ]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 62, 62, 32)        896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 31, 31, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 29, 29, 32)        9248      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 14, 14, 32)       0         
 2D)                                                             
                                                                 
 flatten (Flatten)           (None, 6272)              0         
                                                                 
 dense (Dense)               (None, 128)               8

In [ ]:
# Part 2 - Fitting the CNN to the images

# Using ImageDataGenerator, we create more images with single image, by rotating, tilting, zooming the original image.This is called Image augmentation.
from keras.preprocessing.image import ImageDataGenerator

# rescale the each pixel of image by multiplying each pixel value with the ratio 1/255 = 0.0039
# Shear range slants the shape of the image.
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True 
                                   )

# for test data we dont create extra images.
test_datagen = ImageDataGenerator(rescale = 1./255)

# batch_size = 32 --> at a time take only 32 images to process.
training_set = train_datagen.flow_from_directory('/content/drive/My Drive/dataset/training_set',
                                                 target_size = (64,64),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

test_set = test_datagen.flow_from_directory('/content/drive/My Drive/dataset/test_set',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'categorical')


Found 446 images belonging to 3 classes.
Found 238 images belonging to 3 classes.


In [ ]:
print(type(training_set))
print(type(train_datagen))

<class 'keras.preprocessing.image.DirectoryIterator'>
<class 'keras.preprocessing.image.ImageDataGenerator'>


In [ ]:
classifier.fit_generator(training_set,
                         epochs = 5,
                         shuffle = True
                         )

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  This is separate from the ipykernel package so we can avoid doing imports until


Epoch 1/5
10/14 [====================>.........] - ETA: 22s - loss: 1.1569 - accuracy: 0.4371

/usr/local/lib/python3.7/dist-packages/PIL/Image.py:960: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  "Palette images with Transparency expressed in bytes should be "


14/14 [==============================] - 81s 6s/step - loss: 1.0706 - accuracy: 0.5314
Epoch 2/5
14/14 [==============================] - 16s 1s/step - loss: 0.6118 - accuracy: 0.7668
Epoch 3/5
14/14 [==============================] - 16s 1s/step - loss: 0.4148 - accuracy: 0.8386
Epoch 4/5
14/14 [==============================] - 16s 1s/step - loss: 0.2918 - accuracy: 0.8901
Epoch 5/5
14/14 [==============================] - 16s 1s/step - loss: 0.2656 - accuracy: 0.9058


In [ ]:
import numpy as np
predictions = classifier.predict(test_set)
predictions = np.argmax(predictions,axis=1)

In [ ]:
predictions

array([1, 0, 0, 1, 1, 1, 2, 0, 0, 2, 1, 2, 0, 1, 2, 2, 1, 1, 2, 2, 0, 2,
       1, 0, 1, 1, 2, 1, 1, 0, 2, 0, 2, 1, 0, 0, 2, 1, 2, 1, 0, 0, 1, 1,
       2, 2, 0, 0, 0, 0, 1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 0, 1, 0, 2, 2, 1, 0, 1, 0, 0, 2, 2, 1, 0, 1, 0,
       1, 2, 1, 2, 1, 2, 1, 0, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 0, 0, 2, 1,
       2, 2, 0, 0, 0, 1, 2, 2, 0, 2, 0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 1, 2,
       2, 0, 0, 1, 1, 1, 2, 0, 2, 0, 0, 1, 0, 2, 1, 2, 0, 0, 2, 1, 2, 1,
       1, 1, 0, 2, 2, 0, 2, 1, 1, 0, 2, 1, 2, 1, 0, 2, 0, 1, 0, 1, 0, 2,
       0, 0, 1, 2, 0, 1, 2, 0, 1, 1, 0, 2, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 2, 1, 2, 1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 1, 1, 1, 2, 1,
       2, 2, 0, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 1, 0, 0, 2, 1])

In [ ]:
classes = training_set.class_indices
classes

{'bulbasaur': 0, 'charmander': 1, 'pikachu': 2}

In [ ]:
from PIL import Image
img = Image.open('/content/drive/My Drive/pokemon-img.png')
img = img.resize((64,64))
img2arr = np.array(img)
img2arr = img2arr.reshape(1,64,64,3)
pred = classifier.predict(img2arr)

In [ ]:
np.argmax(pred,axis=1)

array([1])

In [ ]:
img = Image.open('/content/drive/My Drive/pokemon_img_2.png').convert("RGB")
img = img.resize((64,64))
img2arr = np.array(img)
img2arr = img2arr.reshape(1,64,64,3)
pred = classifier.predict(img2arr)

In [ ]:
np.argmax(pred,axis=1)

array([0])